#!/bin/sh

# Create
# Allow local users to create repositories

if [ "$_" != `which su` ]
then
    echo "Only local users can create repositories."
    echo "Tip: Use 'su git' from the root account on this server."
    exit 128
fi

if [ $# -eq 0 ]
then
    echo "You must supply a project name."
    echo "Usage: create <project>"
    exit 128
fi

# Append '.git' to the repository name if needed.
repo_name=`/bin/echo $1 | sed 's/\.git\|$/.git/i'`

if [ -d "$repo_name" ]
then
    echo "This project already exists, remove it first."
    echo "Tip: remove $1"
    exit 128
fi

# Finally create the repository.
git --bare init "$repo_name"
